import { Category, Product, BannerSlide, TrustItem } from "@/types";

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Hogar y decoración",
    slug: "hogar-y-decoracion",
    icon: "Home",
    color: "#FCE4EF",
    sort_order: 1,
    is_active: true,
    item_count: 42,
  },
  {
    id: "cat-2",
    name: "Cocina y comedor",
    slug: "cocina-y-comedor",
    icon: "UtensilsCrossed",
    color: "#EEEAFB",
    sort_order: 2,
    is_active: true,
    item_count: 36,
  },
  {
    id: "cat-3",
    name: "Ropa y accesorios",
    slug: "ropa-y-accesorios",
    icon: "Shirt",
    color: "#DDF3EC",
    sort_order: 3,
    is_active: true,
    item_count: 28,
  },
  {
    id: "cat-4",
    name: "Belleza y cuidado personal",
    slug: "belleza-y-cuidado-personal",
    icon: "Sparkles",
    color: "#FDE8DD",
    sort_order: 4,
    is_active: true,
    item_count: 51,
  },
  {
    id: "cat-5",
    name: "Tecnología y accesorios",
    slug: "tecnologia-y-accesorios",
    icon: "Headphones",
    color: "#E0EEFB",
    sort_order: 5,
    is_active: true,
    item_count: 34,
  },
  {
    id: "cat-6",
    name: "Juguetes y juegos",
    slug: "juguetes-y-juegos",
    icon: "Gamepad2",
    color: "#FFF1CC",
    sort_order: 6,
    is_active: true,
    item_count: 25,
  },
  {
    id: "cat-7",
    name: "Papelería y oficina",
    slug: "papeleria-y-oficina",
    icon: "BookOpen",
    color: "#FCE4EF",
    sort_order: 7,
    is_active: true,
    item_count: 39,
  },
  {
    id: "cat-8",
    name: "Deportes y aire libre",
    slug: "deportes-y-aire-libre",
    icon: "Dumbbell",
    color: "#EEEAFB",
    sort_order: 8,
    is_active: true,
    item_count: 18,
  },
  {
    id: "cat-9",
    name: "Mascotas",
    slug: "mascotas",
    icon: "PawPrint",
    color: "#DDF3EC",
    sort_order: 9,
    is_active: true,
    item_count: 22,
  },
  {
    id: "cat-10",
    name: "Más variedades",
    slug: "mas-variedades",
    icon: "Grid",
    color: "#FFF1CC",
    sort_order: 10,
    is_active: true,
    item_count: 47,
  },
];

export const MOCK_CIRCULAR_CATEGORIES = [
  { name: "Hogar", slug: "hogar-y-decoracion", icon: "Home", bg: "bg-[#FCE4EF]", color: "text-[#6D4BB8]" },
  { name: "Cocina", slug: "cocina-y-comedor", icon: "UtensilsCrossed", bg: "bg-[#EEEAFB]", color: "text-[#6D4BB8]" },
  { name: "Ropa", slug: "ropa-y-accesorios", icon: "Shirt", bg: "bg-[#DDF3EC]", color: "text-[#28795A]" },
  { name: "Belleza", slug: "belleza-y-cuidado-personal", icon: "Sparkles", bg: "bg-[#FDE8DD]", color: "text-[#D25832]" },
  { name: "Tecnología", slug: "tecnologia-y-accesorios", icon: "Headphones", bg: "bg-[#E0EEFB]", color: "text-[#2D73B6]" },
  { name: "Juguetes", slug: "juguetes-y-juegos", icon: "Gamepad2", bg: "bg-[#FFF1CC]", color: "text-[#B37E12]" },
  { name: "Papelería", slug: "papeleria-y-oficina", icon: "BookOpen", bg: "bg-[#FCE4EF]", color: "text-[#D94883]" },
  { name: "Mascotas", slug: "mascotas", icon: "PawPrint", bg: "bg-[#DDF3EC]", color: "text-[#28795A]" },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    category_id: "cat-2",
    category_name: "Cocina y comedor",
    name: "Termo de acero inoxidable 500 ml",
    slug: "termo-de-acero-inoxidable-500-ml",
    description: "Termo con aislamiento al vacío de doble pared. Mantiene bebidas calientes por 12 horas y frías por 24 horas. Tapa hermética antiderrame.",
    detail: "500 ml",
    brand: "AlyHome",
    sku: "COC-TRM-01",
    price: 34900,
    compare_price: 42000,
    stock: 8,
    low_stock_threshold: 3,
    is_active: true,
    is_featured: true,
    rating_avg: 4.9,
    rating_count: 38,
    images: [
      {
        id: "img-1",
        url: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
        sort_order: 1,
        is_primary: true,
      },
    ],
  },
  {
    id: "prod-2",
    category_id: "cat-2",
    category_name: "Cocina y comedor",
    name: "Set de recipientes herméticos x5",
    slug: "set-de-recipientes-hermeticos-x5",
    description: "Juego de 5 recipientes libres de BPA con cierre hermético de silicona. Aptos para microondas, lavavajillas y congelador.",
    detail: "x5 recipientes",
    brand: "AlyHome",
    sku: "COC-REC-05",
    price: 57800,
    compare_price: 68000,
    stock: 2, // low stock -> amber badge
    low_stock_threshold: 3,
    is_active: true,
    is_featured: true,
    rating_avg: 4.8,
    rating_count: 52,
    images: [
      {
        id: "img-2",
        url: "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=600&q=80",
        sort_order: 1,
        is_primary: true,
      },
    ],
  },
  {
    id: "prod-3",
    category_id: "cat-3",
    category_name: "Ropa y accesorios",
    name: "Morral escolar impermeable",
    slug: "morral-escolar-impermeable",
    description: "Morral ergonómico con compartimento acolchado para laptop de hasta 15.6\", bolsillos laterales para termo y tela resistente al agua.",
    detail: "Varios colores",
    brand: "AlyStyle",
    sku: "ROP-MOR-03",
    price: 64900,
    compare_price: 79900,
    stock: 12,
    low_stock_threshold: 3,
    is_active: true,
    is_featured: true,
    rating_avg: 4.9,
    rating_count: 24,
    images: [
      {
        id: "img-3",
        url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
        sort_order: 1,
        is_primary: true,
      },
    ],
  },
  {
    id: "prod-4",
    category_id: "cat-6",
    category_name: "Juguetes y juegos",
    name: "Peluche conejito suave 35 cm",
    slug: "peluche-conejito-suave-35-cm",
    description: "Peluche ultra suave de felpa hipoalergénica, costuras reforzadas y relleno de algodón siliconado. Ideal para regalo.",
    detail: "35 cm",
    brand: "AlyKids",
    sku: "JUG-PEL-04",
    price: 28500,
    compare_price: 35000,
    stock: 5,
    low_stock_threshold: 3,
    is_active: true,
    is_featured: true,
    rating_avg: 5.0,
    rating_count: 19,
    images: [
      {
        id: "img-4",
        url: "https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=600&q=80",
        sort_order: 1,
        is_primary: true,
      },
    ],
  },
  {
    id: "prod-5",
    category_id: "cat-4",
    category_name: "Belleza y cuidado personal",
    name: "Set de cuidado facial con sérum",
    slug: "set-de-cuidado-facial-con-serum",
    description: "Kit completo de rutina facial con sérum de ácido hialurónico, crema hidratante ligera y rodillo de masaje facial.",
    detail: "Kit x3 piezas",
    brand: "AlyGlow",
    sku: "BEL-FAC-05",
    price: 42900,
    compare_price: 54000,
    stock: 3, // low stock -> amber badge
    low_stock_threshold: 3,
    is_active: true,
    is_featured: true,
    rating_avg: 4.9,
    rating_count: 45,
    images: [
      {
        id: "img-5",
        url: "https://images.unsplash.com/photo-1608248597359-561354316a3a?auto=format&fit=crop&w=600&q=80",
        sort_order: 1,
        is_primary: true,
      },
    ],
  },
  {
    id: "prod-6",
    category_id: "cat-5",
    category_name: "Tecnología y accesorios",
    name: "Audífonos inalámbricos Bluetooth",
    slug: "audifonos-inalambricos-bluetooth",
    description: "Conexión Bluetooth 5.3 de baja latencia, estuche de carga rápida con pantalla LED de batería, sonido estéreo nítido y control táctil.",
    detail: "Touch + estuche",
    brand: "AlyTech",
    sku: "TEC-AUD-06",
    price: 49900,
    compare_price: 65000,
    stock: 15,
    low_stock_threshold: 4,
    is_active: true,
    is_featured: true,
    rating_avg: 4.7,
    rating_count: 63,
    images: [
      {
        id: "img-6",
        url: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80",
        sort_order: 1,
        is_primary: true,
      },
    ],
  },
  {
    id: "prod-7",
    category_id: "cat-7",
    category_name: "Papelería y oficina",
    name: "Cuaderno anillado tapa dura x100 hojas",
    slug: "cuaderno-anillado-tapa-dura-x100-hojas",
    description: "Cuaderno de pasta dura con acabado mate soft touch, argollado metálico doble O, papel bond de 90g que no traspasa la tinta.",
    detail: "100 hojas cuadros",
    brand: "AlyNotes",
    sku: "PAP-CUA-07",
    price: 18900,
    compare_price: 24000,
    stock: 20,
    low_stock_threshold: 4,
    is_active: true,
    is_featured: true,
    rating_avg: 4.8,
    rating_count: 31,
    images: [
      {
        id: "img-7",
        url: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
        sort_order: 1,
        is_primary: true,
      },
    ],
  },
  {
    id: "prod-8",
    category_id: "cat-9",
    category_name: "Mascotas",
    name: "Plato comedero para mascota antiderrame",
    slug: "plato-comedero-para-mascota-antiderrame",
    description: "Comedero de acero inoxidable desmontable con base de silicona antideslizante que atrapa salpicaduras. Higiénico y fácil de lavar.",
    detail: "Acero y silicona",
    brand: "AlyPet",
    sku: "MAS-PLA-08",
    price: 22900,
    compare_price: 29900,
    stock: 0, // Out of stock -> Agotado
    low_stock_threshold: 3,
    is_active: true,
    is_featured: true,
    rating_avg: 4.9,
    rating_count: 28,
    images: [
      {
        id: "img-8",
        url: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=600&q=80",
        sort_order: 1,
        is_primary: true,
      },
    ],
  },
];

export const MOCK_BANNERS: BannerSlide[] = [
  {
    id: "banner-1",
    title: "Variedad que",
    highlight_text: "te encanta",
    subtitle: "Productos únicos, útiles y a los mejores precios para ti y tu hogar.",
    cta_text: "¡Descubre más!",
    link: "#productos-destacados",
    image_url: "https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=800&q=80",
    bg_gradient: "from-[#FDE8DD] via-[#FCE4EF] to-[#FFFBF7]",
    sort_order: 1,
    is_active: true,
  },
  {
    id: "banner-2",
    title: "Detalles que",
    highlight_text: "inspiran tu día",
    subtitle: "Artículos seleccionados con amor para consentir a toda tu familia.",
    cta_text: "Ver colecciones",
    link: "#productos-destacados",
    image_url: "https://images.unsplash.com/photo-1513094735237-8f2714d57c13?auto=format&fit=crop&w=800&q=80",
    bg_gradient: "from-[#EEEAFB] via-[#E0EEFB] to-[#FFFBF7]",
    sort_order: 2,
    is_active: true,
  },
  {
    id: "banner-3",
    title: "Envíos rápidos a",
    highlight_text: "toda Colombia",
    subtitle: "Pide fácil por WhatsApp y recibe tus compras directo en tu puerta.",
    cta_text: "Comprar ahora",
    link: "#productos-destacados",
    image_url: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80",
    bg_gradient: "from-[#FFF1CC] via-[#DDF3EC] to-[#FFFBF7]",
    sort_order: 3,
    is_active: true,
  },
];

export const MOCK_TRUST_ITEMS: TrustItem[] = [
  {
    id: "trust-1",
    title: "Envíos a todo el país",
    description: "Rápidos y seguros",
    icon: "Truck",
  },
  {
    id: "trust-2",
    title: "Compra segura",
    description: "Tus datos están protegidos",
    icon: "ShieldCheck",
  },
  {
    id: "trust-3",
    title: "Atención personalizada",
    description: "Estamos para ayudarte",
    icon: "Headphones",
  },
];

export const MOCK_BOTTOM_VALUES = [
  {
    id: "val-1",
    title: "Productos de calidad",
    description: "Seleccionamos lo mejor para ti",
    icon: "Sparkles",
  },
  {
    id: "val-2",
    title: "Envíos rápidos",
    description: "Recibe en la comodidad de tu hogar",
    icon: "PackageCheck",
  },
  {
    id: "val-3",
    title: "Variedad garantizada",
    description: "Siempre algo nuevo para ti",
    icon: "Layers",
  },
];
